// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformDemoLib.Data;

#nullable disable

namespace PlatformDemoApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230905123855_OrderSeeder")]
    partial class OrderSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatformDemoLib.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ContactNo = "6543210",
                            Name = "Michael Curry"
                        },
                        new
                        {
                            Id = 2L,
                            ContactNo = "0654321",
                            Name = "Stephen Jordan"
                        },
                        new
                        {
                            Id = 3L,
                            ContactNo = "1065432",
                            Name = "Kobe Durant"
                        },
                        new
                        {
                            Id = 4L,
                            ContactNo = "2106543",
                            Name = "Kevin Bryant"
                        },
                        new
                        {
                            Id = 5L,
                            ContactNo = "3210654",
                            Name = "Derrick Nowitzki"
                        },
                        new
                        {
                            Id = 6L,
                            ContactNo = "4321065",
                            Name = "Dirk Rose"
                        },
                        new
                        {
                            Id = 7L,
                            ContactNo = "5432106",
                            Name = "Jordan Green"
                        },
                        new
                        {
                            Id = 8L,
                            ContactNo = "1234560",
                            Name = "Jeff Clarkson"
                        },
                        new
                        {
                            Id = 9L,
                            ContactNo = "234501",
                            Name = "Ben Tatum"
                        },
                        new
                        {
                            Id = 10L,
                            ContactNo = "345012",
                            Name = "Jason Simmons"
                        },
                        new
                        {
                            Id = 11L,
                            ContactNo = "450123",
                            Name = "Luka Kidd"
                        },
                        new
                        {
                            Id = 12L,
                            ContactNo = "501234",
                            Name = "Jason Doncic"
                        },
                        new
                        {
                            Id = 13L,
                            ContactNo = "01235",
                            Name = "Kyrie George"
                        });
                });

            modelBuilder.Entity("PlatformDemoLib.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 100m,
                            CustomerId = 1L,
                            OrderNo = "001"
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 200m,
                            CustomerId = 1L,
                            OrderNo = "002"
                        },
                        new
                        {
                            Id = 3L,
                            Amount = 300m,
                            CustomerId = 1L,
                            OrderNo = "003"
                        },
                        new
                        {
                            Id = 4L,
                            Amount = 400m,
                            CustomerId = 1L,
                            OrderNo = "004"
                        },
                        new
                        {
                            Id = 5L,
                            Amount = 500m,
                            CustomerId = 2L,
                            OrderNo = "005"
                        },
                        new
                        {
                            Id = 6L,
                            Amount = 600m,
                            CustomerId = 2L,
                            OrderNo = "006"
                        },
                        new
                        {
                            Id = 7L,
                            Amount = 700m,
                            CustomerId = 3L,
                            OrderNo = "007"
                        },
                        new
                        {
                            Id = 8L,
                            Amount = 800m,
                            CustomerId = 3L,
                            OrderNo = "008"
                        },
                        new
                        {
                            Id = 9L,
                            Amount = 900m,
                            CustomerId = 3L,
                            OrderNo = "009"
                        },
                        new
                        {
                            Id = 10L,
                            Amount = 1000m,
                            CustomerId = 4L,
                            OrderNo = "010"
                        },
                        new
                        {
                            Id = 11L,
                            Amount = 1100m,
                            CustomerId = 4L,
                            OrderNo = "011"
                        },
                        new
                        {
                            Id = 12L,
                            Amount = 1200m,
                            CustomerId = 5L,
                            OrderNo = "012"
                        },
                        new
                        {
                            Id = 13L,
                            Amount = 1300m,
                            CustomerId = 5L,
                            OrderNo = "013"
                        },
                        new
                        {
                            Id = 14L,
                            Amount = 1400m,
                            CustomerId = 8L,
                            OrderNo = "014"
                        },
                        new
                        {
                            Id = 15L,
                            Amount = 1500m,
                            CustomerId = 8L,
                            OrderNo = "015"
                        },
                        new
                        {
                            Id = 16L,
                            Amount = 1600m,
                            CustomerId = 11L,
                            OrderNo = "016"
                        },
                        new
                        {
                            Id = 17L,
                            Amount = 1700m,
                            CustomerId = 11L,
                            OrderNo = "017"
                        },
                        new
                        {
                            Id = 18L,
                            Amount = 1800m,
                            CustomerId = 12L,
                            OrderNo = "018"
                        },
                        new
                        {
                            Id = 19L,
                            Amount = 1900m,
                            CustomerId = 13L,
                            OrderNo = "019"
                        },
                        new
                        {
                            Id = 20L,
                            Amount = 2000m,
                            CustomerId = 6L,
                            OrderNo = "020"
                        },
                        new
                        {
                            Id = 21L,
                            Amount = 2100m,
                            CustomerId = 6L,
                            OrderNo = "021"
                        },
                        new
                        {
                            Id = 22L,
                            Amount = 2200m,
                            CustomerId = 6L,
                            OrderNo = "022"
                        },
                        new
                        {
                            Id = 23L,
                            Amount = 2300m,
                            CustomerId = 6L,
                            OrderNo = "023"
                        },
                        new
                        {
                            Id = 24L,
                            Amount = 2400m,
                            CustomerId = 6L,
                            OrderNo = "024"
                        },
                        new
                        {
                            Id = 25L,
                            Amount = 2500m,
                            CustomerId = 6L,
                            OrderNo = "025"
                        });
                });

            modelBuilder.Entity("PlatformDemoLib.Models.Order", b =>
                {
                    b.HasOne("PlatformDemoLib.Models.Customer", "customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("PlatformDemoLib.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
